# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a279141773e51a917d4cc96bc182c1ed1a5f54cf65606e958f56541715741c754ebafbf021401f6936a0d725fc66764ea31342cde2acc27c1cc884710878f74e

test:
  secret_key_base: 48f11b2c21d8de05a03cad45f2b2fa5c0cb8193a669e41f95d9a79b78d7ee5d1b68b691c985ce35cfb1d8284adf0ddb07850cd1224a9a2b9c3d3580c4e00f04c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
